-- ----------------------------
-- Table structure for SEC_USER
-- ----------------------------
IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N'[dbo].[SEC_USER]') AND type IN ('U'))
	DROP TABLE [dbo].[SEC_USER]
GO

CREATE TABLE [dbo].[SEC_USER] (
  [ID] varchar(50) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [ORG_TYPE] varchar(20) COLLATE Chinese_PRC_CI_AS  NOT NULL,
  [NAME] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [USERNAME] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [PASSWORD] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [SALT] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [SEX] varchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
  [PHONE_NO] varchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [EMAIL] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [LOCKED] bit  NULL,
  [LOCKED_TIME] datetime DEFAULT NULL NULL,
  [EXPIRED] bit  NULL,
  [EXPIRE_TIME] datetime DEFAULT NULL NULL,
  [DELETED] bit DEFAULT ((0)) NULL,
  [CREATE_BY] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [CREATE_NAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [CREATE_TIME] datetime  NULL,
  [UPDATE_BY] varchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [UPDATE_NAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
  [UPDATE_TIME] datetime DEFAULT NULL NULL,
  [CITY_CODE] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [BRANCH_CODE] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [DISTRICT_CODE] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [DISTRICT_NAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [MECHANISM_CODE] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [MECHANISM_NAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
  [ENTRY_DATE] date  NULL,
  [BIRTHDAY] date  NULL,
  [AVATAR_URL] nvarchar(300) COLLATE Chinese_PRC_CI_AS  NULL
)
GO


-- ----------------------------
-- Indexes structure for table SEC_USER
-- ----------------------------
CREATE NONCLUSTERED INDEX [IDX_SEC_USER_ORG_TYPE]
ON [dbo].[SEC_USER] (
  [ORG_TYPE] ASC
)
GO

CREATE NONCLUSTERED INDEX [IDX_SEC_USER_LOCKED]
ON [dbo].[SEC_USER] (
  [LOCKED] ASC
)
GO

CREATE NONCLUSTERED INDEX [IDX_SEC_USER_EXPIRED]
ON [dbo].[SEC_USER] (
  [EXPIRED] ASC
)
GO

CREATE NONCLUSTERED INDEX [IDX_SEC_USER_DELETED]
ON [dbo].[SEC_USER] (
  [DELETED] ASC
)
GO

-- ----------------------------
-- Records of SEC_USER
-- ----------------------------
BEGIN TRANSACTION
GO

INSERT INTO [SEC_USER]([ID], [ORG_TYPE], [NAME], [USERNAME], [PASSWORD], [SALT], [SEX], [PHONE_NO], [EMAIL], [LOCKED], [LOCKED_TIME], [EXPIRED], [EXPIRE_TIME], [DELETED], [CREATE_BY], [CREATE_NAME], [CREATE_TIME], [UPDATE_BY], [UPDATE_NAME], [UPDATE_TIME], [CITY_CODE], [BRANCH_CODE], [DISTRICT_CODE], [DISTRICT_NAME], [MECHANISM_CODE], [MECHANISM_NAME], [ENTRY_DATE], [BIRTHDAY], [AVATAR_URL]) VALUES ('1183662961333968898', 'INSIDE', N'admin', 'admin', NULL, NULL, NULL, '13052253110', NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-03-15', NULL, N'https://pic3.zhimg.com/80/v2-0115da355a5abe2d455855aefc036586_1440w.jpg');
GO

COMMIT
GO

-- ----------------------------
-- Uniques structure for table SEC_USER
-- ----------------------------
ALTER TABLE [dbo].[SEC_USER] ADD CONSTRAINT [UQ__SEC_USER__B15BE12E26F50B94] UNIQUE NONCLUSTERED ([USERNAME] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


-- ----------------------------
-- Primary Key structure for table SEC_USER
-- ----------------------------
ALTER TABLE [dbo].[SEC_USER] ADD CONSTRAINT [PK__SEC_USER__3214EC27CA569581] PRIMARY KEY CLUSTERED ([ID])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

